### ISSUE TITLE
Dash Financial Report [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#10]
# App name
~~dash-vanguard-report~~
dash-financial-report

# App
~~- [x] This app is currently deployed on Dash Gallery: https://dash-gallery.plotly.host/dash-vanguard-report~~
- [x] This app is currently deployed on Dash Gallery: https://dash-gallery.plotly.host/dash-financial-report
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-financial-report

# Current appearance
![2019-05-01 09 24 42 dash-gallery plotly host 98eccd2471a8](https://user-images.githubusercontent.com/15622051/57018868-f8af3380-6bf2-11e9-95b6-bebf7e30024f.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-459475483
<img width="714" alt="52079967-ba0ecc00-2564-11e9-8905-ced598bb8c2d" src="https://user-images.githubusercontent.com/15622051/57018896-0c5a9a00-6bf3-11e9-8266-b57044fb2cbc.png">

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488121910

![](https://user-images.githubusercontent.com/37411533/56994504-4a14df80-6b6d-11e9-83d4-4ff4a7c7afe9.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[vanguard.zip](https://github.com/plotly/dash-sample-apps/files/3183889/vanguard.zip)

**Comment by ycaokris** [comment]
Please note that this app has been renamed to dash-financial-report and deployed on https://dash-gallery.plotly.host/dash-financial-report/.  All trademarks relate to vanguard should be removed
