### ISSUE TITLE
Natural Gas Well Production [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#12]
# App name
dash-oil-and-gas

# App
- [x] This app is currently deployed on Dash Gallery: https://dash-gallery.plotly.host/dash-oil-and-gas/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-oil-and-gas-demo

# Current appearance
![2019-05-01 09 28 07 dash-gallery plotly host 38b87fcf52d7](https://user-images.githubusercontent.com/15622051/57019237-e681c500-6bf3-11e9-82b8-eb62d45d5a17.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-451038434
![50620871-47142600-0ed0-11e9-8241-2dfdbb40fdcc (1)](https://user-images.githubusercontent.com/15622051/57019295-1204af80-6bf4-11e9-9058-76fb0dc484e0.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-483724642

![](https://user-images.githubusercontent.com/37411533/56225420-53fff400-603f-11e9-943d-dc8257bc8e81.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[oil & gas.zip](https://github.com/plotly/dash-sample-apps/files/3183895/oil.gas.zip)

**Comment by shammamah** [comment]
Note on the mobile layout - we're keeping this with a light theme instead of a dark theme.

**Comment by celinehuang** [comment]
> Note on the mobile layout - we're changing this to have a light theme instead of a dark theme.

Is there a mock up of the mobile layout with the light theme?

**Comment by celinehuang** [comment]
> Note on the mobile layout - we're changing this to have a light theme instead of a dark theme.

Is there a light theme mobile mockup for me to look at? @angeladaodao

**Comment by angeladaodao** [comment]
Okay, I will give you a light colour palette for this app
