### ISSUE TITLE
reduce frequency of dash wind streaming requests 

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-sample-apps#134]
# App name
dash-wind-streaming
# Description of bug
At this time this application is making requests very frequently, we could probably improve performance by reducing the frequency of requests while still showing a good example of live streaming 
# Other notes
Suggested by devops team: https://plotly.slack.com/archives/CHLNH6ZTL/p1559755002009900

cc @shammamah to assign out

**Comment by nicolaskruchten** [comment]
@shammamah will this automatically be done in R-land? @Scott-Clone can you make sure you track this change please ? :)

**Comment by nicolaskruchten** [comment]
Ideally for demo purposes this should happen frequently for a minute or two and then slow down in case the page is left open :)

**Comment by Scott-Clone** [comment]
Ok will do!
