### ISSUE TITLE
Google Analytics should be part of all apps

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#138]
It would be best to add the GA code during deployment. 

cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
My basic idea is that all apps could include an `app.index_string` which contains a special comment that CI could search'n'replace with the GA code before deploying. there are likely other approaches also!

**Comment by shammamah** [comment]
We could define an environment variable that contains the GA code (similar to how we have the deployment usernames/passwords here: https://github.com/plotly/dash-sample-apps/blob/5f9a1c90080e75a7fabefe55a7a5415c6919823e/.circleci/config.yml#L30)

I would want to avoid search-and-replace, because it could lead to errors in the app. (This can be avoided if we use a long and random string, but it doesn't make sense for that to be in the app's code because it's so specific to deployment and doesn't really have anything to do with the functionality of the app). 

I think it might be better to search for wherever `app.layout` starts, and insert the code immediately at that line (then move the `app.layout` declaration down). We know that, at that line, `app` has been defined and refers to the correct thing.

What do you think? (I hope that made sense!)

**Comment by nicolaskruchten** [comment]
Search and replace should be pretty trivial and safe (basically replace `<!-- I AM A GA PLACEHOLDER -->` with `a bunch of Javascript` but yeah an environment variable would work also.
