### ISSUE TITLE
3-D Yield Curve [R]

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash-sample-apps#141]
# App name

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [X] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
[attach redesign image here]

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
Closing as per #400
