### ISSUE TITLE
Title, tags and order on gallery

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-sample-apps#147]
The apps in https://dash-gallery.plotly.host/ should be renamed, reordered and retagged as per this spreadsheet: https://docs.google.com/spreadsheets/d/1yWvhYf1K8YkoPYUsnb867ZlKvUWqiiBrpvBQKF8_5eI/edit#gid=0

cc @cldougl @ycaokris

**Comment by nicolaskruchten** [comment]
feedback welcome on the tags, names, and order, of course!

**Comment by shammamah** [comment]
@nicolaskruchten I think this task has been completed -- can we close the issue?

**Comment by nicolaskruchten** [comment]
yes, thanks!
