### ISSUE TITLE
NYC Uber Rides [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#15]
# App name
dashr-uber-rides

# App
- [ ] This app is currently deployed on DashR Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-469068295

![](https://user-images.githubusercontent.com/37411533/53702418-ad37ff00-3dd4-11e9-81ba-66912a6fb53d.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488335359

![](https://user-images.githubusercontent.com/37411533/57028693-bd6e2e00-6c0d-11e9-89c2-4fb1b079d4e8.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[Uber Ride.zip](https://github.com/plotly/dash-sample-apps/files/3183884/Uber.Ride.zip)

**Comment by lundstrj** [comment]
Closing as per #400
