### ISSUE TITLE
Salesforce Dashboard [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#17]
# App name
dashr-salesforce-crm 

# App
- [ ] This app is currently deployed on DashR Gallery: [deployment URL]
- [c] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-453795879

![51079456-7af00800-1695-11e9-947b-7b47e52830d1](https://user-images.githubusercontent.com/15622051/57018549-03b59400-6bf2-11e9-8f5f-cbca0281f9b8.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-483815952

![](https://user-images.githubusercontent.com/37411533/56239207-56be1180-605e-11e9-975e-fed67b7994e8.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
@KPhans is this still relevant?

**Comment by KPhans** [comment]
nope!
