### ISSUE TITLE
NY Oil and Gas Wells [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#18]
# App name
dashr-oil-and-gas

# App
- [ ] This app is currently deployed on DashR Gallery:
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance

<img width="962" alt="Screen Shot 2019-05-01 at 2 25 21 PM" src="https://user-images.githubusercontent.com/48449678/57034461-8e5fb880-6c1d-11e9-9f1c-b98fbcdb65fd.png">

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-451038434
![50620871-47142600-0ed0-11e9-8241-2dfdbb40fdcc (1)](https://user-images.githubusercontent.com/15622051/57019295-1204af80-6bf4-11e9-9058-76fb0dc484e0.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-483724642

![](https://user-images.githubusercontent.com/37411533/56225420-53fff400-603f-11e9-943d-dc8257bc8e81.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[oil & gas.zip](https://github.com/plotly/dash-sample-apps/files/3183893/oil.gas.zip)

**Comment by lundstrj** [comment]
@shammamah @KPhans bump. Is this something we still intend to move forward on and keep around or has the world moved on?

**Comment by KPhans** [comment]
> @shammamah @KPhans bump. Is this something we still intend to move forward on and keep around or has the world moved on?

No this isnt something that is still relevant i believe. We dont deploy R verisons of the apps on gallery, just source code. Styles are up to date. Correct me if I am wrong
