### ISSUE TITLE
Dash Financial Report [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#19]
# App name
dashr-financial-report

# App
- [ ] This app is currently deployed on DashR Gallery: [deployment URL]
- [x] This app is new

# Source code repository
Redesign: https://github.com/plotly/dash-sample-apps/tree/dashr-financial-report/apps/dashr-financial-report

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-459475483
<img width="714" alt="52079967-ba0ecc00-2564-11e9-8905-ced598bb8c2d" src="https://user-images.githubusercontent.com/15622051/57018896-0c5a9a00-6bf3-11e9-8266-b57044fb2cbc.png">

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488121910

![](https://user-images.githubusercontent.com/37411533/56994504-4a14df80-6b6d-11e9-83d4-4ff4a7c7afe9.jpg)

# Playground deployment 
https://dash-playground.plotly.host/dashr-financial-report/

**Comment by ycaokris** [comment]
Re: https://github.com/plotly/dash-financial-report/pull/20  This app has been renamed, all trademarks should be corrected at deployment and merge into monorepo.

**Comment by lundstrj** [comment]
Closing as per #400
