### ISSUE TITLE
Lastodash [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#21]
# App name
dashr-lastodash 

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-469896383

![](https://user-images.githubusercontent.com/37411533/53983738-e8447600-40e5-11e9-9e4b-e360a05fa547.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[LAS report.zip](https://github.com/plotly/dash-sample-apps/files/3183900/LAS.report.zip)

**Comment by lundstrj** [comment]
Closing as per #400
