### ISSUE TITLE
Dash DAQ Function Generator/Oscilloscope

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-sample-apps#227]
# App name
dash-daq-tektronix350

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-tektronix-350
Migrated to https://github.com/plotly/dash-sample-apps/tree/dash-tektronix-350

# Current appearance
### Light theme
![screencapture-dash-playground-plotly-host-dash-daq-tektronix350-2019-07-12-11_14_29](https://user-images.githubusercontent.com/35306149/61138910-533bfa00-a496-11e9-9c00-7558ddafa267.png)

### Dark theme
![screencapture-dash-playground-plotly-host-dash-daq-tektronix350-2019-07-12-11_15_52](https://user-images.githubusercontent.com/35306149/61138992-7666a980-a496-11e9-9110-a08d5f9536f0.png)

# Redesign
<img width="1360" alt="Screen Shot 2019-07-19 at 3 45 51 PM" src="https://user-images.githubusercontent.com/37411533/61561185-4ee68280-aa3c-11e9-9275-19ed54d3ea4f.png">

# Playground deployment 
[url of playground deployment]

**Comment by ronniebugia** [comment]
Is there a mobile layout available for this app?

**Comment by angeladaodao** [comment]
I will also do that

**Comment by angeladaodao** [comment]
[function generator.zip](https://github.com/plotly/dash-sample-apps/files/3412509/function.generator.zip)
