### ISSUE TITLE
Drug Discovery [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#23]
# App name
dashr-drug-discovery

# App
- [ ] This app is currently deployed on DashR Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
![53678438-f5e4a080-3c8c-11e9-8a20-3933dd449ad5](https://user-images.githubusercontent.com/35306149/57198417-90d55180-6f40-11e9-9d0f-b7986e576f61.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488780724

![](https://user-images.githubusercontent.com/37411533/57097732-7dc74500-6ce6-11e9-8c9b-7cfa3d3a7b06.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[drug precusors.zip](https://github.com/plotly/dash-sample-apps/files/3183668/drug.precusors.zip)

**Comment by lundstrj** [comment]
Closing as per #400
