### ISSUE TITLE
ImportError: cannot import name 'ClientsideFunction'

### ISSUE THREAD

**Issue by wisdomtheif** [plotly/dash-sample-apps#230]
When running the dash-oil-and-gas sample app I run into this error. Can anyone explain to me why this is happening and how to fix it?

**Comment by celinehuang** [comment]
Check to make sure you have the right requirements installed (```pip install -r requirements.txt```). If that doesn't work could you post a screenshot of the error so I could get more information?

**Comment by lundstrj** [comment]
@christopherjeon You've worked on this app recently. Is this an issue you have encountered?

**Comment by christopherjeon** [comment]
@lundstrj This wasn't an issue at all with the DDK version. Should I look into it?

**Comment by lundstrj** [comment]
@christopherjeon if this isn't the same app as the one you were working on, then don't worry about it. I'll take a look to see if this is still relevant. Thanks for offering though.

**Comment by wisdomtheif** [comment]
Hey,

It was an environment issue, issue closed.

**Comment by lundstrj** [comment]
@wisdomtheif thanks for updating!
