### ISSUE TITLE
MRI Reconstruction [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#25]
# App name
dashr-brain-surface-viewer

# App
- [ ] This app is currently deployed on DashR Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-462442220

![image](https://user-images.githubusercontent.com/15622051/57783555-5451e480-76fc-11e9-90a9-f23430117d86.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488130571

![](https://user-images.githubusercontent.com/37411533/56996127-9e21c300-6b71-11e9-9a6b-c25f616a96b5.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[MRI reconstruction.zip](https://github.com/plotly/dash-sample-apps/files/3183878/MRI.reconstruction.zip)

**Comment by lundstrj** [comment]
@KPhans bump. Is this relevant still?

**Comment by KPhans** [comment]
@lundstrj nope!
