### ISSUE TITLE
Phylogeny trees [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#26]
# App name
dash-phylogeny

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/dash-phylogeny/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-phylogeny

# Current appearance
![2019-05-01 12 43 48 dash-gallery plotly host 3012a26ec7b0](https://user-images.githubusercontent.com/15622051/57029112-cd3a4200-6c0e-11e9-8373-fc12c9fc9a69.png)

# Redesign
![Phylogeny trees-01-min](https://user-images.githubusercontent.com/37411533/57949755-45f9f900-78b3-11e9-8d81-3f6b19fd32bb.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[Phylogeny trees.ai.zip](https://github.com/plotly/dash-sample-apps/files/3192707/Phylogeny.trees.ai.zip)

**Comment by angeladaodao** [comment]
mobile version:

[Phylogeny trees mobile.ai.zip](https://github.com/plotly/dash-sample-apps/files/3263106/Phylogeny.trees.mobile.ai.zip)
