### ISSUE TITLE
Phylogeny trees [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#27]
# App name
dashr-phylogeny

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
![image](https://user-images.githubusercontent.com/15622051/58988172-09813500-87af-11e9-9b5a-c524436c40dd.png)

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
@sacul-git bump. Should we still keep this issue around?

**Comment by sacul-git** [comment]
This issue can be closed (the app is in master already).
