### ISSUE TITLE
[R] Dash Monthly Fund Report 

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#270]
# App name
dash-monthly-fund-report

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-goldman-sachs-report-demo

# Current appearance
![image](https://user-images.githubusercontent.com/15622051/62635521-db7eb500-b905-11e9-9d4f-023ea1a41968.png)

# Redesign
![image](https://user-images.githubusercontent.com/15622051/62635677-1aad0600-b906-11e9-985d-a0bc0ec56b5c.png)

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
Closing as per #400
