### ISSUE TITLE
Cytoscape Phylogeny [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#28]
# App name
cytoscape-phylogeny

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/cytoscape-phylogeny/
- [ ] This app is new

# Source code repository
https://dash.plot.ly/cytoscape/biopython

# Current appearance
![2019-05-01 12 46 46 dash-gallery plotly host d629ea5a641c](https://user-images.githubusercontent.com/15622051/57029250-33bf6000-6c0f-11e9-8902-46bc01dd2d01.png)

# Redesign
![cytoscape-phylogeny app-01-min](https://user-images.githubusercontent.com/37411533/58729628-ed992000-83b7-11e9-9408-1e3ee0d06ef1.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by shammamah** [comment]
@angeladaodao When you redesign this, please try to make it look similar to https://nextstrain.org/zika?dmin=2016-12-03!

**Comment by angeladaodao** [comment]
[cytoscape-phylogeny app.ai.zip](https://github.com/plotly/dash-sample-apps/files/3242627/cytoscape-phylogeny.app.ai.zip)

**Comment by ronniebugia** [comment]
Is there a mobile mock up for this app?

**Comment by lundstrj** [comment]
this one seems to be all kinds of merged.
