### ISSUE TITLE
Code review and polish existing R examples in dash-sample-apps

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash-sample-apps#284]
As part of our continuing efforts to further improve the gallery, we should make a second pass over the current set of Dash for R apps to ensure that they meet coding standards -- essentially, we want our demos to reflect R idioms and best practices. Some of these have been summarized elsewhere:

https://style.tidyverse.org
https://google.github.io/styleguide/Rguide.html

If each of us takes on 3 apps, we can review each other's work pretty quickly. I think this will be  a great opportunity to show off what everyone has learned this summer!

**Comment by lundstrj** [comment]
@rpkyle while I admire the ambition and the reasoning, it also looks like we didn't get this done before the end of the summer. There are other ongoing efforts to review and lift the sample apps so I'm closing this. Feel free to reopen if you think this is a mistake.
