### ISSUE TITLE
US Opioid Epidemic [R] 

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#30]
# App name
dashr-opioid-epidemic

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-455840062

![](https://user-images.githubusercontent.com/37411533/51435722-5e7f3d00-1c4c-11e9-9187-698a9f28bb54.jpg)

![](https://user-images.githubusercontent.com/37411533/51435727-63dc8780-1c4c-11e9-82b5-0252ecddcacb.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-484241765

![](https://user-images.githubusercontent.com/37411533/56317546-019c0180-612b-11e9-8f69-043d9c557f81.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[US opioid.zip](https://github.com/plotly/dash-sample-apps/files/3183869/US.opioid.zip)

**Comment by lundstrj** [comment]
Closing as per #400
