### ISSUE TITLE
Object Detection [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#32]
# App name
dashr-object-detection

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-456527638

![](https://user-images.githubusercontent.com/37411533/51559709-9fe03a00-1e50-11e9-907f-4b545a219fc5.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-483724813

![](https://user-images.githubusercontent.com/37411533/56225437-5eba8900-603f-11e9-84ab-41b001b8daa7.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[object detection.zip](https://github.com/plotly/dash-sample-apps/files/3183826/object.detection.zip)

**Comment by lundstrj** [comment]
Closing as per #400
