### ISSUE TITLE
dash-tsne no tsne_3d.csv file !

### ISSUE THREAD

**Issue by johncleveland** [plotly/dash-sample-apps#328]
One cannot use the full local version as there is no tsne_3d.csv file. How does one obtain this file?

**Comment by kuilef** [comment]
I found it in the folder dash-sample-apps\apps\dashr-tsne\data 
But it doesn't help - as usual - there is more errors later in local.py file :(

**Comment by johncleveland** [comment]
Have you gotten the local version to work?

**Comment by kuilef** [comment]
yes, put that file to needed directory and also change app.py

**Comment by johncleveland** [comment]
thnx. I will try it this weekend.

**Comment by lundstrj** [comment]
tsne_3d.csv was removed (on purpose) on May 24th 2019 but for some reason local.py wasn't updated (there are also a few lingering references in the dashr-tsne app).

Give me a second to investigate.

**Comment by lundstrj** [comment]
@johncleveland @kuilef What changes did you do to app.py (apart from uncommentating:
`from local import local_layout, local_callbacks`?

When I run `python app.py` in the current master branch, with tsne_3d.csv copied over from dashr-tsne/data and the local imports enabled, I don't really get any different data or behavior in the actual app than I did before I made these changes. Did you do more changes? What data or functionality did you gain after your changes?

**Comment by lundstrj** [comment]
@xhlulu do you know?

**Comment by kuilef** [comment]
@lundstrj honestly, I don't remember, I deleted whole app several months ago.

**Comment by lundstrj** [comment]
@kuilef Okay. Thanks for getting back to me. Maybe I'll close this one and make a new issue to remove all references to tsne_3d.csv in both apps, and possibly to remove local.py as it looks like unused code.

**Comment by lundstrj** [comment]
Seems like the idea with local.py is to allow you to re-run to recalculate recomputed data for this app. I should patch local.py to not need the missing file.

**Comment by lundstrj** [comment]
tsne_3d.csv is pretty central to local.py I don't see any straight forward way to removing the need for that file.

**Comment by Einlar** [comment]
> @johncleveland @kuilef What changes did you do to app.py (apart from uncommentating:
> `from local import local_layout, local_callbacks`?
> 
> When I run `python app.py` in the current master branch, with tsne_3d.csv copied over from dashr-tsne/data and the local imports enabled, I don't really get any different data or behavior in the actual app than I did before I made these changes. Did you do more changes? What data or functionality did you gain after your changes?

I get the correct behaviour by also changing:
`app.layout = local_layout
local_callbacks(app)`
And removing the previous lines reffering to the demo.
