### ISSUE TITLE
Visualize Model Training [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#33]
# App name
dash-live-model-training

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/dash-live-model-training/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-live-model-training

# Current appearance
![2019-05-01 13 30 22 dash-gallery plotly host 4f67df1c4bd9](https://user-images.githubusercontent.com/15622051/57031278-4c327900-6c15-11e9-98df-af17908b1b4f.png)

# Redesign
The long instruction of the app down there will be in a popup window while people click on "Learn more" button

![live model training viewer-01-min](https://user-images.githubusercontent.com/37411533/57888983-9749b000-7801-11e9-9c00-e976037ea641.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[live model training viewer.ai.zip](https://github.com/plotly/dash-sample-apps/files/3189125/live.model.training.viewer.ai.zip)

**Comment by celinehuang** [comment]
@angeladaodao is there a mobile layout for this app?

**Comment by angeladaodao** [comment]
Will do on really quick

**Comment by angeladaodao** [comment]
Here is the mobile view of this app
[live model training mobile.ai.zip](https://github.com/plotly/dash-sample-apps/files/3225002/live.model.training.mobile.ai.zip)
