### ISSUE TITLE
Visualize Model training [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#34]
# App name
dashr-live-model-training

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
[attach redesign image here]

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
Closing as per #400
