### ISSUE TITLE
dash-nlp poor handling of banks with few complaints

### ISSUE THREAD

**Issue by lundstrj** [plotly/dash-sample-apps#346]
# App name
dash-nlp

# Description of bug
Wordcloud fails when run on too few bank complaints

# How to replicate the bug
launch app
select a small sample size
select a bank with less than 11 logged complaints

# Other notes
We have a fix bundled up with the precomputing effort.

**Comment by ycaokris** [comment]
@lundstrj  We will need more detailed information/solution regarding this issue

**Comment by lundstrj** [comment]
patched, merged and deployed to playground and gallery.
