### ISSUE TITLE
dash-nlp TypeError in lda_analysis

### ISSUE THREAD

**Issue by dataxienxe** [plotly/dash-sample-apps#348]
# App name
dash-nlp

# Description of bug
Followed the instructions to git clone the app and while I'm able to run it normally, the LDA graph is not working. There is a TypeError in ldacomplaints.py.
This is the error message: 
`File "C:\Users\dash-sample-apps\apps\dash-nlp\app.py", line 705, in update_lda_table
complaints_text, list(STOPWORDS)
File "C:\Users\apps\dash-nlp\ldacomplaints.py", line 51, in lda_analysis
df = df[pd.notnull(df["Consumer complaint narrative"])]
TypeError: list indices must be integers or slices, not str`

I'm not able to find a solution to this. Can anyone please help?

**Comment by oxananu** [comment]
@dataxienxe I am not able to reproduce this error with the latest version of master. Are you selecting some specific bank? Did you manage to install all the requirements?

**Comment by lundstrj** [comment]
dash-nlp has had it's LDA analysis heavily refactored since this issue was opened.
