### ISSUE TITLE
Edit Procfile for dash-nlp app

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-sample-apps#357]
Refering to https://github.com/plotly/dash-sample-apps/pull/356#discussion_r345476169

We are editing predeploy.py for adding google tag manager to all apps via circle-ci deployment.  This requires a consistent `app:server`(or `index:server`) instead of `app:SERVER` in Procfile and dash-nlp was skipped. 

It is suggested to change `web: gunicorn --pythonpath apps/dash-nlp app:SERVER` to `web: gunicorn --pythonpath apps/dash-nlp app:server` in order for deploying to production getting triggered. 

'server' in [app body](https://github.com/plotly/dash-sample-apps/blob/2369e4152f5243fc6bcf24c412998529e511b309/apps/dash-nlp/app.py#L592) needs to be changed accordingly.

**Comment by lundstrj** [comment]
This was fixed in the mentioned #358
