### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by OGANICA** [plotly/dash-sample-apps#359]

**Comment by lundstrj** [comment]
@OGANICA Could you perhaps give us a little bit more context?
When did you get this error? What were you trying to do? What version of Dash, Python were you using? We'd love to help out but don't really know where to start in this case.

**Comment by lundstrj** [comment]
Unable to reproduce. Assuming stale. Please reopen if you think it is a mistake to close and/or if you have more information to add.
