### ISSUE TITLE
Image Processing [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#36]
# App name
dashr-image-processing

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-460422521

![](https://user-images.githubusercontent.com/37411533/52238841-00349a00-289b-11e9-8560-4edfac9f0c9a.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488137015

![](https://user-images.githubusercontent.com/37411533/56997158-d8d92a80-6b74-11e9-81af-587b3269a8c4.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[image process.zip](https://github.com/plotly/dash-sample-apps/files/3183847/image.process.zip)

**Comment by lundstrj** [comment]
Closing as per #400
