### ISSUE TITLE
[sample-apps] error: RPC failed

### ISSUE THREAD

**Issue by lundstrj** [plotly/dash-sample-apps#360]
# App name

# Description of bug
error: RPC failed

https://github.com/plotly/streambed/issues/11813
https://github.com/plotly/streambed/issues/12011
https://github.com/plotly/streambed/issues/12308
https://github.com/plotly/streambed/issues/12107
https://github.com/plotly/streambed/issues/12217

# How to replicate the bug

# Other notes
[dash-nlp 78a5ac84] Deployed commit: 0444f4c9fe229d54e75d69edf48ad6f0a72dcd3f
 1 file changed, 1 insertion(+)
 create mode 100644 apps/dash-nlp/assets/plotly_ga.js
Counting objects: 29131, done.
Delta compression using up to 36 threads.
Compressing objects: 100% (12984/12984), done.
Writing objects: 100% (29131/29131), 808.90 MiB | 176.36 MiB/s, done.
Total 29131 (delta 14402), reused 28680 (delta 14019)
remote: Resolving deltas: 100% (14402/14402), done.        
remote: Checking connectivity: 36, done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
Exited with code 1

**Comment by bpostlethwaite** [comment]
I checked this out. Two problems (more may remain) but both hidden by the CI output. I had to SSH into machine and run commands within the container to get the actual error messages. Those ended up being quite clear though problematic in and if themselves.
But solving this issue IMO is a matter of making sure the actual error messages are output to the CCI UI. 
Then we can solve the other problems with more concise issues.

**Comment by bpostlethwaite** [comment]
Oh hmmm that was for a different bug actually. Point stands, but deserves its own issue.

**Comment by lundstrj** [comment]
@bpostlethwaite bump.
(feel free to point me in the general direction of someone else if you are busy or they would be better suited for this).

I think a workaround could be to force deploy the new, fixed, app code and thus bypassing this CI issue (but then also not making our CI more robust).

**Comment by bpostlethwaite** [comment]
> I think a workaround could be to force deploy the new, fixed, app code and thus bypassing this CI issue (but then also not making our CI more robust).

:100: Agreed. Let's solve these case by case by deploying themselves until we build up our own internal understanding of how things _should_ work then do it properly. 

Let's unlink CI

**Comment by lundstrj** [comment]
https://github.com/plotly/streambed/issues/13743
