### ISSUE TITLE
Interactive t-SNE [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#38]
# App name
dashr-tsne

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-461590032

![](https://user-images.githubusercontent.com/37411533/52445378-f019f600-2af8-11e9-8721-e9105bcb3e12.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488090333

![](https://user-images.githubusercontent.com/37411533/56989020-6dd12900-6b5f-11e9-9c38-36855b87f85c.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[t-sne.zip](https://github.com/plotly/dash-sample-apps/files/3183858/t-sne.zip)

**Comment by lundstrj** [comment]
Closing as per #400
