### ISSUE TITLE
Explore SVMs [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#40]
# App name
dashr-svm

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-461590032

![](https://user-images.githubusercontent.com/37411533/52441588-0ae76d00-2aef-11e9-9aa9-69d339920e93.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488423715

![57042343-6169d080-6c32-11e9-990a-ed98843fa9d6](https://user-images.githubusercontent.com/15622051/57784047-3b95fe80-76fd-11e9-806a-11d76a0717fa.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[SVM.zip](https://github.com/plotly/dash-sample-apps/files/3183860/SVM.zip)

**Comment by lundstrj** [comment]
Closing as per #400
