### ISSUE TITLE
Purge stale issues

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash-sample-apps#400]
Following up on offline correspondence with @lundstrj, several stale (prior to release last summer) Dash for R-related issues can be purged from `dash-sample-apps` at this time, as these apps are now finished and in the gallery.

#270,  #141,  #98,  #70,  #68,  #66,  #64,  #59,  #57,  #55,  #48,  #46,  #44,  #40,  #38,  #36,  #34,  #32,  #30,  #23,  #21,  #19,  #15.

**Comment by lundstrj** [comment]
@rpkyle we cleaned up a lot of old issues and PRs. Is there anything else you think we can clean up at this stage or should we call the cleanup done?

**Comment by rpkyle** [comment]
@lundstrj Looking at https://github.com/plotly/dash-sample-apps/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adashr, I see only two Dash for R-related issues, and both are current.

Thanks for all your work on cleaning up the repo, I'll close this one since I think we're in good shape now.
