### ISSUE TITLE
Pylinter test failed with circle-ci

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-sample-apps#406]
This merge https://github.com/plotly/dash-sample-apps/pull/405 into master has broke black check.  Looks like `flake8` only inspects instead of fix changes, and the moment I apply black pylinter in another branch keeps breaking ci check.

**Comment by jbampton** [comment]
You can use autopep8 to fix Flake8 issues.  The command below runs inplace recursive aggressive.
``` 
autopep8 -i -r -a -a --select=E203,E265,E711,W291 .
```

**Comment by josegonzalez** [comment]
This is related to E203 which was introduced in #405. It's not actually a PEP8 rule, just a pet peeve to do it a certain way. This is covered [here](https://github.com/psf/black#slices) in the psf's black docs.

Filing a PR to remove E203 and apply `black`.
