### ISSUE TITLE
Color picker CSS in Oscilloscope app

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-sample-apps#412]
# App name

Dash DAQ: Function Generator & Oscilloscope Control Panel

# Description of bug

The color picker CSS looks messed up. Can we just delete it the color picker altogether? Pretty unnecessary IMO.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1865834/75507210-6dd3cc80-59ae-11ea-8969-350985aae96c.png">

# How to replicate the bug

https://dash-gallery.plotly.host/dash-daq-tektronix350/

# Other notes

**Comment by lundstrj** [comment]
@AirballClaytonCalvin this might be a good task to look at

**Comment by AirballClaytonCalvin** [comment]
@lundstrj This looks appropriate for my current skills set. Taking a look now. 

The limiting factor for me right now is having a solid understanding of version control and not making any irreparable changes.

**Comment by AirballClaytonCalvin** [comment]
@lundstrj I have taken out the colorpicker and changed the size of some of the html.divs so they line up. 

Next step: I'll do walk through the changes I made with one of the solutions people tomorrow -> They will show me how to deploy on Playground.

**Comment by lundstrj** [comment]
@jackparmer the app looks OK and the changes are deployed to the gallery. I'm closing this for now but please do reopen if you'd like us to do something differently.
