### ISSUE TITLE
Dash Manufacture Example - Issues with Multi Outputs

### ISSUE THREAD

**Issue by Z-Knight** [plotly/dash-sample-apps#414]
# App name
dash-manufacture-spc-dashboard

# Description of bug
The manufacture demo app does not function correctly in the current released version on github:
https://github.com/plotly/dash-sample-apps/tree/master/apps/dash-manufacture-spc-dashboard

but does work correctly on the demo site:
https://dash-gallery.plotly.host/dash-manufacture-spc-dashboard/

Specifically, the 'Specification Setting' tab in the demo does not function in the github release - the problem is that there are 4 rows of "Specs" in that example, and each of the 4 rows have a "Historical Value" that is populated. In addition, the "Set new value" section should have 4 corresponding values populated but in the GITHUB version only the 1st one "Upper Specification limit" is actually populated with data - the remaining 3 rows are empty. This functions CORRECTLY in the DEMO version (2nd link above). The issue on the GITHUB version is that there are multi 'Outputs' associated with the pulldown menu - but only the 1st Output is getting populated with correct data.

The issue seems to be with this callback ...only the 'us_usl_input' value is populated - the other outputs below it are not.

`
@app.callback(
--
  |   | output=Output("value-setter-store", "data"),
  |   | inputs=[Input("value-setter-set-btn", "n_clicks")],
  |   | state=[
  |   | State("metric-select-dropdown", "value"),
  |   | State("value-setter-store", "data"),
  |   | State("ud_usl_input", "value"),
  |   | State("ud_lsl_input", "value"),
  |   | State("ud_ucl_input", "value"),
  |   | State("ud_lcl_input", "value"),
  |   | ],
  |   | )
`

# How to replicate the bug
Checkout/Clone the dash examples and run the 'dash-manufacture-spc-dashboard/' demo. When the page opens up, go to the "Specification Settings" tab. You will notice that there are 4 rows of data on the far right. The data in the "Set new value" column will only be visible for the 1st row - not the other 3 rows. Do the same for the demo link above and you will see that this demo functions correctly - each of the rows is fully populated with data.

# Other notes

**Comment by lundstrj** [comment]
@AirballClaytonCalvin wan't to take a look at this one too?

**Comment by AirballClaytonCalvin** [comment]
@Z-Knight I am unable to reproduce this issue. Can you please comment the requirements that you have installed? You can grab this using the command below:

**pip list|grep dash**

**Comment by Z-Knight** [comment]
Unfortunately I cannot do that at the moment - not until next thursday. The reason is that this is installed on a co-worker's computer and he is on vacation till next wed. In the meantime, can I ask what you are seeking? Are you wanting to get which version of dash it is - whether it is greater than the 0.40 version where the multi-output capability was added? I can confirm that we have a latest version - I can't tell you numerically which one, but we basically did a clean new install of conda and plotly last week, so I assume that we had the latest. I can try to replicate the install on my computer in the next couple of days so I may amend my comment/issue if I discover that I don't have the problem. Thanks for trying to help out.

**Comment by Z-Knight** [comment]
I installed this on my own - outside of what my co-worker did - and I do NOT have a problem as I originally noted in the issue.

It appears to be a configuration problem with his setup - he may may be fully updated as I initially thought. I will keep the issue open for this week but will likely close it out next week after he returns. Sorry for the trouble and thanks for checking for me.

**Comment by lundstrj** [comment]
@Z-Knight no no, thank you for taking the time and effort to open an issue and to then also engage with us. We really do appreciate it. Sometimes it's a local issue, other times it's a real problem that needs fixing. If I had actual internet points to had out, you'd have some coming your way.

**Comment by AirballClaytonCalvin** [comment]
Yup. I second what @lundstrj said. Thanks for getting in touch @Z-Knight . I will investigate a little further. If you do come across the issue again, please take a screen shot.

**Comment by Z-Knight** [comment]
yeah, thanks for the follow-up. Fyi, I did a second setup on virtual box and downloaded the latest everything and it works fine - no multi-output issues. So I will close this issue and when my co-worker gets back and I make it through this Zombie Apocalypse then I will try to figure out what is outdated on his setup. Thank you.
