### ISSUE TITLE
dash-daq-tektronix350 requirements.txt conflict

### ISSUE THREAD

**Issue by lundstrj** [plotly/dash-sample-apps#416]
I was going to look at this but I think I stumbled over a requirements conflict.
requirements.txt states:
```
gunicorn==19.9.0
dash==1.0.0
numpy==1.16.1
scipy==1.2.1
dash-daq==0.3.0

```
But dash-daq 0.3.0 demands dash 1.6.2 or greater
`ERROR: dash-daq 0.3.0 has requirement dash>=1.6.0, but you'll have dash 1.0.0 which is incompatible.`

I can't install the dependencies for this app as things are stated right now. How did you guys do it?

_Originally posted by @lundstrj in https://github.com/plotly/dash-sample-apps/pull/415#issuecomment-598700538_

**Comment by lundstrj** [comment]
@AirballClaytonCalvin want to look at this one too?

**Comment by AirballClaytonCalvin** [comment]
Yup. I'll take a look at this
