### ISSUE TITLE
Outdated gallery thumbnail for Oscilloscope app

### ISSUE THREAD

**Issue by lundstrj** [plotly/dash-sample-apps#417]
# App name
Dash DAQ: Function Generator & Oscilloscope Control Panel
# Description of bug
The gallery thumbnail is no longer accurate (we removed the color picker as per #412 
# How to replicate the bug
https://dash-gallery.plotly.host/Portal/
# Other notes
![Screenshot 2020-03-16 at 12 33 31](https://user-images.githubusercontent.com/1045735/76754647-c662e200-6782-11ea-8369-9a1598af21a7.png)

**Comment by lundstrj** [comment]
@AirballClaytonCalvin want to take this one too?

**Comment by AirballClaytonCalvin** [comment]
Updated!
