### ISSUE TITLE
Change text and color background

### ISSUE THREAD

**Issue by mdiego1595** [plotly/dash-sample-apps#420]
# App name
MANUFACTURING SPC DASHBOARD

# Description of question:
Hi,
how can I change the text and background color of this dashboard?

Thank you

**Comment by ycaokris** [comment]
@mdiego1595  Thanks for opening this issue. Customized css in dash applications could be added as static assets(please refer to [our docs](https://dash.plotly.com/external-resources) for more information), this is done by stylesheet in `assets/` folder, which will be served to the browser when your app runs and loads.

To modify css attribute in this app, simply edit font color and background color in this file https://github.com/plotly/dash-sample-apps/blob/master/apps/dash-manufacture-spc-dashboard/assets/spc-custom-styles.css#L20 

There are multiple sections in this app so you may need to modify more than one html tag to apply a whole-page css change.

Please let me know if you have further issues.
