### ISSUE TITLE
Dash Playground login

### ISSUE THREAD

**Issue by peterdsharpe** [plotly/dash-sample-apps#422]
Hi all,

I'm hoping to contribute an app to the Dash App Gallery (specifically, this one: https://github.com/peterdsharpe/AeroSandbox-Interactive-Demo), but I'm having trouble following the steps in `README.md` under "Adding a new app".

In particular, I'm having trouble logging in to Dash Playground. My credentials from http://plot.ly don't seem to work here, and when I navigate from the [login screen](https://playground.plotly.host/Auth/login/?next=/Auth/o/authorize/%3Fresponse_type%3Dtoken%26client_id%3DeC5Tuezee6eebahn5xo9moo4edai2weepheethah%26redirect_uri%3Dhttps%3A//dash-playground.plotly.host/Manager/oauth2-redirect%26state%3DPortal#/) -> ["Forgot Password"](https://playground.plotly.host/Auth/password/reset/) -> ["Sign Up"](https://playground.plotly.host/Auth/login/?action=signup), I'm simply taken back to the initial login screen.

I'm not sure this is the right place to open this trivial issue, but would you happen to know how I could go about creating credentials for Dash Playground?

Thanks and sorry for the trouble!

**Comment by jackparmer** [comment]
Hey Peter, this is awesome! Our team should be able to take it from here and deploy to the gallery for you. I'll share your email internally in case @josegonzalez 's team has any questions. Cheers!

**Comment by peterdsharpe** [comment]
Thanks so much Jack & team! :)

**Comment by josegonzalez** [comment]
Just a note: this is now deployed to our gallery :)

**Comment by peterdsharpe** [comment]
@josegonzalez 
Looks amazing Jose, thanks so much!

For future app updates with new features, what would be the best way for me to push these up to the Gallery? Whatever method's easiest for your team is fine by me!

**Comment by josegonzalez** [comment]
@peterdsharpe For future updates, you can PR changes to this repository, and someone on our team will review it/get it merged. Also, feel free to email me - you have my email now - should you have concerns that you want to express in private.

Thanks again!
