### ISSUE TITLE
Lock down mapbox token for sample apps

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-sample-apps#426]
PR https://github.com/plotly/dash-sample-apps/pull/425 was intended to rotate mapbox token to our dedicated one which has current limitations as @nicolaskruchten mentioned:

- those tokens aren't locked to gallery domains, some apps use versions of Plotly.js might be too old for the locking to work
- the old public token is still active

In order to totally deprecate the old token, we should
- remove all hard-coded mapbox token from these apps
- verify that apps with a new token are loading map correctly, and remove all customized mapbox style (if there is, like this line  https://github.com/plotly/dash-sample-apps/blob/139acc6b751d277fcd8a7c08f3f9277f3aad9aaa/apps/dash-opioid-epidemic/app.py#L86) , or replace with strings like "basic", "satellite", etc, check [plotly mapbox reference](https://plotly.com/python/mapbox-layers/).
- set new token as env variables and add instructions in readme.

**Comment by nicolaskruchten** [comment]
Thanks @ycaokris!

I actually think the easiest thing to do might be to upgrade DCC and/or plotly.js (via the assets trick) so that we can lock down the token that's in this repo. In principle this should "just work" :)

**Comment by ycaokris** [comment]
> Thanks @ycaokris!
> 
> I actually think the easiest thing to do might be to upgrade DCC and/or plotly.js (via the assets trick) so that we can lock down the token that's in this repo. In principle this should "just work" :)

yep, that will work as well! Needs a package update(dash, dcc) for apps that are related and verify that domain restriction works.  I believe testing out domain-locked token will need a deployment and won't work when running locally?

**Comment by nicolaskruchten** [comment]
That's right.

**Comment by sstripps1** [comment]
The following apps were modified in https://github.com/plotly/dash-sample-apps/pull/425:

- [ ] dash-daq-satellite-dashboard
- [ ] dash-medical-provider-charges
- [ ] dash-oil-and-gas
- [ ] dash-oil-and-gas-ternary
- [ ] dash-opioid-epidemic
- [ ] dash-phylogeny
- [ ] dash-spatial-clustering
- [ ] dash-uber-rides-demo
- [ ] dashr-medical-provider-charges
- [ ] dashr-oil-and-gas-ternary
- [ ] dashr-oil-and-gas
- [ ] dashr-opiod-endemic
- [ ] dashr-uber-rasterizer
- [ ] dashr-uber-rides

I'll go through the list and update `dcc` / perform some QA

**Comment by sstripps1** [comment]
When adding the domain restriction to the token, dash-medical-provider-charges and dash-opioid-epidemic break - I've removed the restriction for now, and will add it back once I've upgraded dash on both of these apps

**Comment by sstripps1** [comment]
All necessary apps have been upgraded, and the domain restriction has been put in place.

cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Great, thank you!
