### ISSUE TITLE
Wind Speed Measurement [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#43]
# App name
dash-wind-streaming

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/dash-wind-stream
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-wind-streaming

# Current appearance
![2019-05-01 13 46 04 dash-gallery plotly host bfd34b55bb77](https://user-images.githubusercontent.com/15622051/57032090-7edd7100-6c17-11e9-820c-8b4e5b0a2193.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-463430412

![](https://user-images.githubusercontent.com/37411533/52759850-688e2480-2fdb-11e9-993c-d09e64d4c90c.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488393768

![image](https://user-images.githubusercontent.com/15622051/57783835-d6daa400-76fc-11e9-85a4-f1efd124982c.png)

# Playground deployment 
https://dash-playground.plotly.host/dash-wind-streaming/

**Comment by chriskfwoo** [comment]
Redesigned: 

![image](https://user-images.githubusercontent.com/15094206/57553481-a54c8c00-733c-11e9-8854-ce0314e82a13.png)
