### ISSUE TITLE
Wind Speed Measurement [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#44]
# App name
dashr-wind-stream

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-463430412

![](https://user-images.githubusercontent.com/37411533/52759850-688e2480-2fdb-11e9-993c-d09e64d4c90c.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488393768

![image](https://user-images.githubusercontent.com/15622051/57783799-c5919780-76fc-11e9-9e57-ebf9d9f455ed.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[wind speed.zip](https://github.com/plotly/dash-sample-apps/files/3183723/wind.speed.zip)

**Comment by lundstrj** [comment]
Closing as per #400
