### ISSUE TITLE
Forex Trader Demo [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#45]
# App name
dash-web-trader

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/dash-web-trader/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-web-trader

## App bug fix
- [ ] Changes in https://github.com/plotly/dash-web-trader/pull/8/files to resolve issue https://github.com/plotly/dash-web-trader/issues/6 should be added to this app.

# Current appearance
![2019-05-01 14 38 33 dash-gallery plotly host 70e6aa3975af](https://user-images.githubusercontent.com/15622051/57035058-1eeac880-6c1f-11e9-9afe-99965c998f3e.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-456940372

![](https://user-images.githubusercontent.com/37411533/51632543-8fe25c00-1f1d-11e9-9717-6064d2564afe.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488846914

![](https://user-images.githubusercontent.com/37411533/57109481-94c86000-6d03-11e9-94cc-935f435b1466.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by nicolaskruchten** [comment]
@chriskfwoo can you please incorporate the changes from https://github.com/plotly/dash-web-trader/pull/8 into the new Python version? these are to prevent the app from not-booting when it can't connect to the external news source

**Comment by chriskfwoo** [comment]
>@chriskfwoo can you please incorporate the changes from https://github.com/plotly/dash-web-trader/pull/8 into the new Python version? these are to prevent the app from not-booting when it can't connect to the external news source

@nicolaskruchten Yup! However, it might take a while to push to playground since the redesign and refactor will be a long process. 

Does this need to be a quick hotfix?

**Comment by ycaokris** [comment]
> > @chriskfwoo can you please incorporate the changes from [plotly/dash-web-trader#8](https://github.com/plotly/dash-web-trader/pull/8) into the new Python version? these are to prevent the app from not-booting when it can't connect to the external news source
> 
> @nicolaskruchten Yup! However, it might take a while to push to playground since the redesign and refactor will be a long process.
> 
> Does this need to be a quick hotfix?

I've deployed to gallery via original fixed branch manually. Just make sure monorepo has included this changes before auto-deployment.
