### ISSUE TITLE
Use colorblind-friendly sequence of colors for trainable segmentation app

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-sample-apps#450]
# App name

https://dash-gallery.plotly.host/dash-image-segmentation/

# Description of bug

The sequence of colors used for annotations is not colorblind-friendly. The `Plotly` or `d3` sets of colors in https://plotly.com/python/discrete-color/ would be better

**Comment by nicholas-esterer** [comment]
This is a good idea although I would reckon not all sets of colours map to highly differentiated greys. For example, I had this problem when wanting a digital version of some figures in colour but also wanting them to be interpretable when printed in greyscale. I found that sampling uniformly from the `px.colors.sequential.magma` colormap gave nicely differentiated greys and colours.

**Comment by emmanuelle** [comment]
Do you think people could want to print the webpage in greyscale? For research papers one has to find colors which both print well in grayscale and are colorblind-friendly but for an interactive web app I think very few people will want a print-out, let alone in greyscale.

**Comment by nicholas-esterer** [comment]
I guess I'm assuming greyscale = colorblind friendly, but maybe that's not the case? Is there a recommended colormap?

**Comment by emmanuelle** [comment]
Well there are of course a lot of different types of colorblindness, but some types are more frequent than other. In particular, not distinguishing well red and green is one of the most common problems. See for example https://venngage.com/blog/color-blind-friendly-palette/
