### ISSUE TITLE
How to make Dash App Gallery (like the one at https://dash-gallery.plotly.host/Portal)

### ISSUE THREAD

**Issue by zeluspudding** [plotly/dash-sample-apps#455]
Title says it all - I see that lots of the dash documentation and example apps have been open sourced but I can't seem to locate code for the gallery page at https://dash-gallery.plotly.host/Portal. 

Can someone point me to it? That would be awesome :)

**Comment by josegonzalez** [comment]
The software serving the Dash App Gallery portal is part of our [Dash Enterprise](https://plotly.com/dash/) offering, which includes a number of features:

- Commercial dash libraries such as [Dash Design Kit](https://plotly.com/dash/design-kit/) and [Dash Snapshots](https://plotly.com/dash/snapshot-engine/)
- Our [Dash App Manager](https://plotly.com/dash/app-manager/), which provides an easy-to-use deployment method and the aforementioned Dash App Portal.
- Dash [Workspaces](https://plotly.com/dash/workspaces/), an quick way to get started developing Dash apps in a Cloud IDE or Jupyter notebooks.
- [Kubernetes integration](https://plotly.com/dash/kubernetes/), for running workloads at scale.

The above - and much more! - are available via Dash Enterprise. If you're interested in learning more, feel free to email me - `jose @ plotly.com` (without spaces) - and we'll be in touch :)
