### ISSUE TITLE
Add link to source code to trainable segmentation and bounding box app

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-sample-apps#457]
See for example https://dash-gallery.plotly.host/dash-volcano-plot/ and the "view on github" button.

**Comment by emmanuelle** [comment]
@surchs another good issue to get started.

**Comment by surchs** [comment]
@emmanuelle as you pointed out, the "view on github" functionality comes from [layout_helper](https://github.com/plotly/dash-bio/blob/81bb6fa257febb59d7841f8c5573e7231f5a9095/tests/dashbio_demos/common/layout_helper.py#L9) in `dash-bio-demo` and makes a number of assumptions on where to find the source code based on the app name. I don't think there is something similar for `dash-sample-apps`. 

I could make this link explicitly in the app but we would then have to copy it to other apps if they should also have this feature. Do you think we should make a shared module for the layout of the `dash-sample-apps` as well?

**Comment by surchs** [comment]
Closed in #506
