### ISSUE TITLE
Forex Trader Demo [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#46]
# App name
dashr-web-trader

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-456940372

![](https://user-images.githubusercontent.com/37411533/51632543-8fe25c00-1f1d-11e9-9717-6064d2564afe.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488846914

![](https://user-images.githubusercontent.com/37411533/57109481-94c86000-6d03-11e9-94cc-935f435b1466.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[forex trader.zip](https://github.com/plotly/dash-sample-apps/files/3183718/forex.trader.zip)

**Comment by lundstrj** [comment]
Closing as per #400
