### ISSUE TITLE
Multi-page Financial Report [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#47]
# App name
dash-multipage-report

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-464218342

![](https://user-images.githubusercontent.com/37411533/52888061-3fd76d80-3148-11e9-82a1-c246b7b51aad.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488325138

![](https://user-images.githubusercontent.com/37411533/57026855-cc061680-6c08-11e9-9968-3475eeece089.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
@rpkyle I'm calling it. Please reopen if you think we should pick this up.

**Comment by rpkyle** [comment]
> @rpkyle I'm calling it. Please reopen if you think we should pick this up.

I believe Carlone finished the Python version also, but somehow this issue was not updated to reflect this. @shammamah might be able to confirm.

**Comment by lundstrj** [comment]
@rpkyle thanks for the context. It helps me going forward.

**Comment by shammamah** [comment]
@rpkyle @lundstrj Yes, he did finish the Python version too.
