### ISSUE TITLE
Multi-page Financial Report [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#48]
# App name
dashr-multipage-report
(Note that this app is not currently on gallery: https://community.plot.ly/t/goldman-sachs-dash-app-link/9206/4)

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-goldman-sachs-report-demo

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-464974728

![screen shot 2019-02-19 at 11 54 31 am](https://user-images.githubusercontent.com/37411533/53032668-44986c00-343d-11e9-9fb8-4765eed3e07d.png)

![screen shot 2019-02-19 at 11 54 41 am](https://user-images.githubusercontent.com/37411533/53032676-48c48980-343d-11e9-9a96-05e08efbdb59.png)

![screen shot 2019-02-19 at 11 54 53 am](https://user-images.githubusercontent.com/37411533/53032688-524df180-343d-11e9-893f-06d513da68c4.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[financial report.zip](https://github.com/plotly/dash-sample-apps/files/3183693/financial.report.zip)

**Comment by lundstrj** [comment]
Closing as per #400
