### ISSUE TITLE
Dash Ocean Optics [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#49]
# App name
dash-ocean-optics

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/dash-ocean-optics/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-ocean-optics

# Current appearance
![2019-05-01 14 31 49 dash-gallery plotly host fba3f865af1a](https://user-images.githubusercontent.com/15622051/57034569-de3e7f80-6c1d-11e9-8c50-30aabab3521f.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-461605010

![](https://user-images.githubusercontent.com/37411533/52444496-8ac50580-2af6-11e9-8a0a-9028713bc039.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-488857616

![](https://user-images.githubusercontent.com/37411533/57111316-ae6ca600-6d09-11e9-833b-d0a988161aea.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[ocean optics.zip](https://github.com/plotly/dash-sample-apps/files/3183715/ocean.optics.zip)
