### ISSUE TITLE
Add modal with some explanations to bounding box app

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-sample-apps#499]
The [modal component of `dbc`](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/modal/) could be used here.  

Also, one could update the code of the trainable segmentation app to use dbc's modal, since the code is not very nice at the moment.

**Comment by emmanuelle** [comment]
@surchs this could be a good issue to get started.

**Comment by surchs** [comment]
Closed in #506
