### ISSUE TITLE
bounding box app throws server error when set up in conda environment

### ISSUE THREAD

**Issue by surchs** [plotly/dash-sample-apps#502]
# App name
[dash-image-annotation](https://github.com/plotly/dash-sample-apps/tree/master/apps/dash-image-annotation)

# Description of bug
When started from a fresh conda environment with dependencies installed as per the [Readme](https://github.com/plotly/dash-sample-apps/blob/master/apps/dash-image-annotation/README.md), `dash-image-annotation` throws several errors in the browser console ([see gist](https://gist.github.com/surchs/59933181e65cc18ce097452076341a41)) and does not load correctly:
![image](https://user-images.githubusercontent.com/1302022/94924683-ff974100-048b-11eb-93cf-22dd558ce012.png)

there is also a (maybe unrelated) error thrown in the python log:
```
[2020-10-02 08:30:36,350] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/dash/dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/surchs/conda/envs/bbox/lib/python3.8/site-packages/dash/dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "app.py", line 313, in modify_table_entries
    if "shapes" in graph_relayoutData.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

When started from a fresh virtual environment (and installing dependencies from `requirements.txt`), the app starts correctly without errors (browser or python): 
![image](https://user-images.githubusercontent.com/1302022/94924882-56047f80-048c-11eb-8c87-4ba8a1935858.png)

Installing the dependencies through conda with `conda install --file requirements.txt` also results in a larger number of installed dependencies than when doing the same with pip (`pip install -r requirements.txt`:

```
➜ conda list | wc
     95     288    5650
```
vs
```
➜ pip freeze | wc
     34      34     579
```
I have also dumped the installed modules in the gist.

# How to replicate the bug
1. create fresh conda environment e.g. `conda create -n test -y && conda activate test`
2. install dependencies `conda install --file requirements.txt -y`
3. start dash-image-annotation `python app.py`
# Other notes
I have taken a quick look at some other dash example apps and found that they appear to work when set up in a conda environment

**Comment by emmanuelle** [comment]
Thanks for reporting this issue @surchs. I believe the error message in the Python log is a minor callback bug unrelated to the display problem. I could solve the display problem by
- unpinning the numpy version, since 0.18.3 does not seem to be exist for conda (I ended up unpinning everything but only numpy was a problem)
- and using the conda-forge channel since I believe this is the recommended channel for installing dash-related packages via conda, `conda install -c conda-forge -y --file requirements.txt`, and probably using the main conda channels there were some package incompatibilities (??).

@surchs could you please check that these two steps solve the issue? 

@nicolaskruchten should we give more instructions to conda users in dash-sample-apps, and make sure the requirements.txt works for conda as well ? A lot of people using windows or mac use conda instead of pip/venv.

**Comment by surchs** [comment]
@emmanuelle I can confirm that unpinning the numpy version to >= 0.18.3 and installing with conda-forge fixes the issue

**Comment by emmanuelle** [comment]
@surchs ok cool. FYI the way I investigated was to google "dash conda" and then I found on https://anaconda.org/conda-forge/dash that conda-forge was the recommended channel, I think I had known this at some point but I had forgotten :-).

**Comment by surchs** [comment]
ah cool, thanks for that! I'll keep tracking conda-forge then for testing things.
