### ISSUE TITLE
Dash DAQ IV Curve Tracer [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#51]
# App name
dash-daq-iv-tracer

# App
- [x] This app is currently deployed on Dash(R) Gallery: https://dash-gallery.plotly.host/dash-daq-iv-tracer/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-daq-iv-tracer

# Current appearance
![2019-05-01 14 35 39 dash-gallery plotly host 82184651ddeb](https://user-images.githubusercontent.com/15622051/57034830-92d8a100-6c1e-11e9-9f65-359d708dee9d.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-462200706

![](https://user-images.githubusercontent.com/37411533/52542877-50679c80-2d72-11e9-8531-dd1fd254e885.png)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-483772227

![](https://user-images.githubusercontent.com/37411533/56231834-641ed000-604d-11e9-9ddd-571d5b818cb4.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[IV Tracer.zip](https://github.com/plotly/dash-sample-apps/files/3183906/IV.Tracer.zip)

**Comment by lundstrj** [comment]
Looks like this just wasn't closed after the code was merged.
