### ISSUE TITLE
Clone a specific app

### ISSUE THREAD

**Issue by SoufianeDataFan** [plotly/dash-sample-apps#526]
Hi, 

is it possible to clone one specific app name instead of importing all the repository? 

Thanks,

**Comment by xhlulu** [comment]
Hi it's now possible to do that thanks to the automatic release introduced in https://github.com/plotly/dash-sample-apps/pull/560

See [instructions here](https://github.com/plotly/dash-sample-apps#downloading-and-running-a-single-app)
