### ISSUE TITLE
Dash DAQ Satellite Dashboard

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#53]
# App name
dash-daq-satellite-dashboard

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-daq-satellite-dashboard

# Current appearance
[attach screenshot of current app here]

# Redesign

![Satellite Dashboard-01-min](https://user-images.githubusercontent.com/37411533/61154802-146d6a80-a4bd-11e9-8cdd-f00fac03ba5a.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[Satellite Dashboard.ai.zip](https://github.com/plotly/dash-sample-apps/files/3387813/Satellite.Dashboard.ai.zip)

**Comment by lundstrj** [comment]
Looks like this just wasn't closed even though the code has been merged.
