### ISSUE TITLE
Clinical Analytics [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#55]
# App name
dashr-clinical-analytics

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
Link: https://github.com/plotly/streambed/issues/12759#issuecomment-478965069

![image](https://user-images.githubusercontent.com/15622051/57102944-86257d00-6cf2-11e9-89da-1042c88eb2c0.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[clinic analytics.ai.zip](https://github.com/plotly/dash-sample-apps/files/3183866/clinic.analytics.ai.zip)

**Comment by lundstrj** [comment]
Closing as per #400
