### ISSUE TITLE
Auto-release and upload individual apps as zip files

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-sample-apps#559]
I experimented with github actions in [my personal repo](https://github.com/xhlulu/dash-sample-apps/blob/master/.github/workflows/main.yml) to automatically bump the version and release new versions of this repository every time a commit is pushed to `master` along **with the zip file of each app in `apps/`**.  I don't think the versioning adheres to semver, but by doing so it would be possible to download individual apps as a zip file instead of the entire repo (and history). 

For example:
```bash
wget https://github.com/plotly/dash-sample-apps/releases/latest/download/<appname>.zip
unzip <appname>.zip
cd <appname>/
pip install -r requirements.txt
python app.py
```

@alexcjohnson @nicolaskruchten thoughts on this?

**Comment by alexcjohnson** [comment]
Interesting idea... cc @chriddyp

**Comment by chriddyp** [comment]
I like it!

**Comment by xhlulu** [comment]
Awesome! PR here https://github.com/plotly/dash-sample-apps/pull/560
