### ISSUE TITLE
Medical Provider Charges Dashboard [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#56]
# App name
dash-medical-provider-charges

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-medical-provider-charges

# Current appearance
![screenshot](https://user-images.githubusercontent.com/35306149/57901474-5a96ac80-7833-11e9-9ed5-728ed9f0e447.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12759#issuecomment-480682419

![hospital cost-01](https://user-images.githubusercontent.com/37411533/57956597-8499ae80-78c7-11e9-874a-82b88a1c6eb7.jpg)

# Playground deployment 
https://dash-playground.plotly.host/dash-medical-provider-charges/

**Comment by angeladaodao** [comment]
[hospital cost.ai 2.zip](https://github.com/plotly/dash-sample-apps/files/3193121/hospital.cost.ai.2.zip)
