### ISSUE TITLE
avs-dash-explorer cannot load local glb or json files?

### ISSUE THREAD

**Issue by foggyweather** [plotly/dash-sample-apps#563]
I want to load these two fields from local files in my project folder:

![image](https://user-images.githubusercontent.com/79210806/108225219-06250d00-713c-11eb-9555-dbb73a6eb635.png)

I have saved locally the .json file with the timings and I have all the .glb frames saved in a folder.

Even if I try to do this:
![image](https://user-images.githubusercontent.com/79210806/108225458-3f5d7d00-713c-11eb-80c7-ef21cc7ea96d.png)

(Basically, I download separately the .json and I give the path but I keep the streamed glb files)
In this case, the dashboard is still blank:

![image](https://user-images.githubusercontent.com/79210806/108225605-6156ff80-713c-11eb-9fbd-73b573053395.png)

Is it possible to load the .glb and the .json from the local folder?

**Comment by xhlulu** [comment]
I haven't tried using local files for this demo, but it might be worth trying to place the files inside your assets folder and link to the assets path with `app.get_asset_url`

**Comment by foggyweather** [comment]
> I haven't tried using local files for this demo, but it might be worth trying to place the files inside your assets folder and link to the assets path with `app.get_asset_url`

This actually worked fine after a few attempts. Frames are in the assets folder as you suggested, thanks!

![image](https://user-images.githubusercontent.com/79210806/108324360-171b6000-71c8-11eb-81e1-275cab1c3984.png)

**Comment by xhlulu** [comment]
Phew, glad it worked! Closing this issue since it's solved, but if you run into more problems with local loading feel free to reopen :)
