### ISSUE TITLE
Medical Provider Charges Dashboard [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#57]
# App name
dashr-medical-provider-charges

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-sample-apps/tree/dash-medical-provider-charges/apps/dash-medical-provider-charges

# Current appearance
![screenshot](https://user-images.githubusercontent.com/35306149/57948655-39c06c80-78b0-11e9-8641-c95fa10b5080.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12759#issuecomment-480682419

![image](https://user-images.githubusercontent.com/15622051/57103051-ca188200-6cf2-11e9-98fc-30b757e2c254.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[hospital cost.ai.zip](https://github.com/plotly/dash-sample-apps/files/3183702/hospital.cost.ai.zip)

**Comment by lundstrj** [comment]
Closing as per #400
