### ISSUE TITLE
SPC Dashboard [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#58]
# App name
dash-manufacture-spc-dashboard

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-manufacture-spc-dashboard

# Current appearance
![2019-05-02 16 03 55 dash-playground plotly host a757dfc0312b](https://user-images.githubusercontent.com/15622051/57103494-ecf76600-6cf3-11e9-9a7c-90856252bf3b.png)

# Redesign
![SPC dashboard-01-min](https://user-images.githubusercontent.com/37411533/57880904-f8678880-77ed-11e9-9bfd-e6b6bb192560.jpg)
![SPC dashboard-02](https://user-images.githubusercontent.com/37411533/57882157-0d91e680-77f1-11e9-9789-14bd7eddd23f.jpg)

# Playground deployment 
https://dash-playground.plotly.host/dash-manufacture-spc-dashboard/

**Comment by angeladaodao** [comment]
[SPC dashboard.ai.zip](https://github.com/plotly/dash-sample-apps/files/3188684/SPC.dashboard.ai.zip)
