### ISSUE TITLE
Oil and Gas Ternary Diagram [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#60]
# App name
dash-oil-and-gas-ternary

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-oil-gas-ternary

# Current appearance

![2019-05-02 16 10 57 dash-playground plotly host 78a77b4919f9](https://user-images.githubusercontent.com/15622051/57103873-ea494080-6cf4-11e9-9758-58822b138c74.png)

# Redesign
![oil and gas ternary map-01-min](https://user-images.githubusercontent.com/37411533/57483691-669fce80-7275-11e9-9033-60eabd3e451d.jpg)

# Playground deployment 
https://dash-playground.plotly.host/dash-oil-gas-ternary/

**Comment by angeladaodao** [comment]
Plz slack me for the design file whoever gonna do this app

**Comment by shammamah** [comment]
@YunkeXiao Could you try to keep a max height for the `dcc.Dropdown`? You can check this out for some inspiration: https://github.com/plotly/dash-bio/blob/d16a10d7a4444c37b8da3a515171100594b46b20/assets/clustergram-style.css#L126
