### ISSUE TITLE
MapD Example [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#61]
# App name
dash-mapd-demo

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-sample-apps/tree/dash-mapd-demo

# Current appearance
<img width="1424" alt="Screen Shot 2019-05-15 at 1 33 45 PM" src="https://user-images.githubusercontent.com/35306149/57796376-2c6f7a80-7716-11e9-838b-46d5d8229100.png">

# Redesign
![US Flight-01-min](https://user-images.githubusercontent.com/37411533/58284699-29f5cc00-7d79-11e9-855a-9c057c8cf184.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[US Flight.ai.zip](https://github.com/plotly/dash-sample-apps/files/3214074/US.Flight.ai.zip)
