### ISSUE TITLE
Yield Analysis [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#63]
# App name
https://github.com/plotly/streambed/issues/12555 (replace with app name when app is created)

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
[attach redesign image here]

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
I'm going to go ahead a call it. We wont prioritize this any time soon. Feel free to reopen if you disagree.
