### ISSUE TITLE
Dash Entity Recognition

### ISSUE THREAD

**Issue by firmai** [plotly/dash-sample-apps#635]
Hi there, I am having a look at this app, and I am trying to create a convicing example for my unit for me to go ahead with a project, I really like the text color schemes on your app. I think it has been out since around October, it would be lovely if you could make available a version, and if not possible, maybe comment on how to create the text highlighting features. 

https://dash-demo.plotly.host/named-entity-recognition/

Thanks for all the work!

**Comment by xhlulu** [comment]
@firmai Hi, I posted an answer that shows how to reproduce Spacy's NER highlighting using `html`. [You can find it here](https://stackoverflow.com/questions/66708474/is-there-a-way-to-render-spacys-ner-output-on-a-dash-dashboard). Adding callback should be fairly straightforward, though you might need to use the `dash-component-boilerplate` to create a react component if you want it to happen client-side (without callback)

**Comment by firmai** [comment]
Excellent thanks Xing, I will give it a shot next week.
