### ISSUE TITLE
Reduce size of CSVs, GIFs, and Images

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-sample-apps#649]
This PR addresses the issue of GIFs: https://github.com/plotly/dash-sample-apps/pull/648

The code used to significantly reduce GIFs (resizing, heavy optimization):
```bash
files=$(find apps/dashr* -type f -name '*.gif')

for file in $files; do
    gifsicle -O3 --colors 128 --resize-fit-height 800 -o $file $file
done
```

To remove intermediary frames in GIFs:
```bash
gifsicle -U $file `seq -f "#%g" 0 2 370` -O3 -o $file
```

**Comment by xhlulu** [comment]
With a quick filtering find/grep, we get a total of 500MB in csv files:
```bash
find ./ -type f -name '*.csv' -size +5M -exec du -csh {} + | grep total$                                                                                                            
# => 498M    total                                      
```

Could use this python code to compress some of the csv files:

```python
import os
import gzip
from glob import glob
import shutil

from tqdm.auto import tqdm

def convert_to_gz(file, min_size=5*1e6):
    if os.path.getsize(file) > min_size:
        with open(file, 'rb') as f_in:
            with gzip.open(file+'.gz', 'wb') as f_out:
                shutil.copyfileobj(f_in, f_out)

files = glob('**/*.csv', recursive=True)
len(files)

for file in tqdm(files):
    convert_to_gz(file)
```

Which is significantly smaller:
```bash
find ./ -type f -name '*.csv.gz' -exec du -csh {} + | grep total$
# => 101M    total
```

**Comment by xhlulu** [comment]
For images, we could convert pngs to jpg. tho we'd only save <100MB in space:
```bash
find ./ -type f -name '*.png' -exec du -csh {} + | grep total$
# => 55M     total

**Comment by xhlulu** [comment]
To remove intermediary frames in GIFs:
```bash
gifsicle -U $file `seq -f "#%g" 0 2 370` -O2 -o $file
```

**Comment by xhlulu** [comment]
@HammadTheOne Hey can you read `csv.gz` files just like you read `csv` files in R? E.g. 

```R
EURUSD <- fread(file.path("pairs", "EURUSD.csv.gz"))
```

**Comment by HammadTheOne** [comment]
@xhlulu  We definitely can read `csv.gz` with `fread` in R. Based on the [docs](https://rdatatable.gitlab.io/data.table/library/data.table/html/fread.html) the only change we would need to make is adding the `R.utils` dependency to our `init.R` file for the sample app.

> Compressed files with extension ‘.gz’ and ‘.bz2’ are supported if the R.utils package is installed.

**Comment by xhlulu** [comment]
Closed in https://github.com/plotly/dash-sample-apps/pull/648 and https://github.com/plotly/dash-sample-apps/pull/659
