### ISSUE TITLE
Image Stitching and Registration [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#67]
# App name
dash-stitching

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/plotly/dash-stitching

# Current appearance
![image](https://user-images.githubusercontent.com/15622051/57104637-dc94ba80-6cf6-11e9-9905-d948a5174fc6.png)
![image](https://user-images.githubusercontent.com/15622051/57104641-e0c0d800-6cf6-11e9-969f-5870c21329e2.png)
![image](https://user-images.githubusercontent.com/15622051/57104646-e4ecf580-6cf6-11e9-9578-c1561a1708f4.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12554#issuecomment-469492272
![image](https://user-images.githubusercontent.com/15622051/57104587-b96a0b00-6cf6-11e9-82a3-39b5cdc22ecd.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[stitching app.ai.zip](https://github.com/plotly/dash-sample-apps/files/3183677/stitching.app.ai.zip)
