### ISSUE TITLE
Oil and Gas Ternary Diagram [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#68]
# App name
dashr-oil-and-gas-ternary

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
[attach redesign image here]
![image](https://user-images.githubusercontent.com/15622051/57782511-5f0b7a00-76fa-11e9-8117-b850bcded67d.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[oil and gas ternary map.ai.zip](https://github.com/plotly/dash-sample-apps/files/3183680/oil.and.gas.ternary.map.ai.zip)

**Comment by lundstrj** [comment]
Closing as per #400
