### ISSUE TITLE
PKCalc [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#70]
# App name
dashr-pk-calc

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
[attach screenshot of current app here]

# Redesign
![image](https://user-images.githubusercontent.com/15622051/57161793-71142100-6dba-11e9-8225-637e2e01b60c.png)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[pharmacokinetics analysis.ai.zip](https://github.com/plotly/dash-sample-apps/files/3183709/pharmacokinetics.analysis.ai.zip)

**Comment by lundstrj** [comment]
Closing as per #400
