### ISSUE TITLE
Handle relative paths for assets

### ISSUE THREAD

**Issue by chriskfwoo** [plotly/dash-sample-apps#74]
Just a small suggestion for future devs!

In the README.md,

> File paths must be specified relative to the root directory. So, for example, if you have a file 'data.csv' in your app folder my_dash_app/ you will have to refer to this data file as apps/my_dash_app/data.csv within your app.py file.`

I suggest using [Pathlib](https://docs.python.org/3/library/pathlib.html) for more flexibility. 

We could do something like this:

 `BASE_ASSETS_PATH = pathlib.Path(__file__, "/assets").resolve()` in the app.py. 
Then,  `LOGO_PATH = str(BASE_ASSETS_PATH.joinpath("demo.png").resolve())`

See this commit for a working example. [Link](https://github.com/plotly/dash-sample-apps/commit/b60fbd951961942e0c76211da1820aa00e3859c7)

This allows me to run the app at the root level and project level successfully. 

cc @shammamah

**Comment by shammamah** [comment]
@chriskfwoo I love this idea! Would you mind modifying the "Reading files from within an app" section in the README to include some info about Pathlib? 

It might be a better idea to have a pattern for the apps in which `APP_PATH` is defined using Pathlib, and then all files can be accessed relative to that with the `os` library. So, e.g., 

```
APP_PATH = str(pathlib.Path(__file__).resolve())

with open(os.path.join(APP_PATH, 'somefile.txt') as f:
    some_string = f.read()
```

This looks a bit more readable, IMO. Let me know your thoughts on it!

**Comment by chriskfwoo** [comment]
> @chriskfwoo I love this idea! Would you mind modifying the "Reading files from within an app" section in the README to include some info about Pathlib?
> 
> It might be a better idea to have a pattern for the apps in which `APP_PATH` is defined using Pathlib, and then all files can be accessed relative to that with the `os` library. So, e.g.,
> 
> ```
> APP_PATH = str(pathlib.Path(__file__).resolve())
> 
> with open(os.path.join(APP_PATH, 'somefile.txt') as f:
>     some_string = f.read()
> ```
> 
> This looks a bit more readable, IMO. Let me know your thoughts on it!

Looks good!
I updated the readme in this [PR](https://github.com/plotly/dash-sample-apps/pull/81)
