### ISSUE TITLE
Salesforce Dashboard [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#8]
# App name
dash-salesforce-crm 

# App
- [x] This app is currently deployed on Dash Gallery: https://dash-gallery.plotly.host/dash-salesforce-crm
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-salesforce-crm

# Current appearance
![2019-05-01 09 04 15 dash-gallery plotly host e605326fd994](https://user-images.githubusercontent.com/15622051/57018506-d10b9b80-6bf1-11e9-9ed3-444391ab93cf.png)

# Redesign
Link: https://github.com/plotly/streambed/issues/12068#issuecomment-453795879

![51079456-7af00800-1695-11e9-947b-7b47e52830d1](https://user-images.githubusercontent.com/15622051/57018549-03b59400-6bf2-11e9-8f5f-cbca0281f9b8.jpg)

Link: https://github.com/plotly/streambed/issues/12879#issuecomment-483815952

![](https://user-images.githubusercontent.com/37411533/56239207-56be1180-605e-11e9-975e-fed67b7994e8.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[CRM app.zip](https://github.com/plotly/dash-sample-apps/files/3183897/CRM.app.zip)

**Comment by lundstrj** [comment]
Looks merged.
