### ISSUE TITLE
3D Yield Curve [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#9]
# App name
dash-yield-curve

# App
- [x] This app is currently deployed on Dash Gallery: https://dash-gallery.plotly.host/dash-yield-curve/
- [ ] This app is new

# Source code repository
https://github.com/plotly/dash-yield-curve

# Current appearance
![2019-05-01 09 21 34 dash-gallery plotly host 828ed4ab3290](https://user-images.githubusercontent.com/15622051/57018743-90f8e880-6bf2-11e9-9675-d29d1ae122ab.png)

# Redesign
<img width="907" alt="Screen Shot 2019-07-08 at 3 19 59 PM" src="https://user-images.githubusercontent.com/37411533/60836543-e4a82500-a193-11e9-9971-bc23e0954bdb.png">

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[yield curve app.ai.zip](https://github.com/plotly/dash-sample-apps/files/3369891/yield.curve.app.ai.zip)
