### ISSUE TITLE
Animal Study Browser [PYTHON]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#97]
# App name
dash-animal-study-browser

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
https://github.com/shday/studybrowser

# Current appearance
![image](https://user-images.githubusercontent.com/15622051/58118999-05122500-7bd0-11e9-80e9-eeb78f4239f5.png)

# Redesign
![Animal Study Browser-01](https://user-images.githubusercontent.com/37411533/58222521-4f84c600-7ce4-11e9-81e4-4e9350d64e39.jpg)

# Playground deployment 
[url of playground deployment]

**Comment by angeladaodao** [comment]
[Animal Study Browser.ai.zip](https://github.com/plotly/dash-sample-apps/files/3210081/Animal.Study.Browser.ai.zip)

**Comment by shammamah** [comment]
@ronniebugia Please note that there have been some updates to the code here: https://github.com/shday/studybrowser

Can you integrate these changes into your app and then work on the redesign?
