### ISSUE TITLE
Animal Study Browser [R]

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-sample-apps#98]
# App name
dashr-animal-study-browser

# App
- [ ] This app is currently deployed on Dash(R) Gallery: [deployment URL]
- [x] This app is new

# Source code repository
[source code repo URL]

# Current appearance
![image](https://user-images.githubusercontent.com/15622051/58119064-28d56b00-7bd0-11e9-9e66-eeefca821c39.png)

# Redesign
![image](https://user-images.githubusercontent.com/15622051/58423755-dda1d900-8063-11e9-83bf-ad125702a43f.png)

# Playground deployment 
[url of playground deployment]

**Comment by lundstrj** [comment]
Closing as per #400
